// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgje1juAhSrN2bSyuVS1pq6K_rK2lST7U',
    appId: '1:494484064061:web:8dd4e7a040a7691d8ce754',
    messagingSenderId: '494484064061',
    projectId: 'ecomapp-18dc3',
    authDomain: 'ecomapp-18dc3.firebaseapp.com',
    storageBucket: 'ecomapp-18dc3.appspot.com',
    measurementId: 'G-RKL9P7DVPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7GZzcQFwZb8wZVngnXns5yVywpUcyHGY',
    appId: '1:494484064061:android:128108d68f515cf88ce754',
    messagingSenderId: '494484064061',
    projectId: 'ecomapp-18dc3',
    storageBucket: 'ecomapp-18dc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrZH72-VlVo90qJJ_j-2bVPmb42CcifrA',
    appId: '1:494484064061:ios:f2a00c9aa22e66918ce754',
    messagingSenderId: '494484064061',
    projectId: 'ecomapp-18dc3',
    storageBucket: 'ecomapp-18dc3.appspot.com',
    iosBundleId: 'com.example.ecomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrZH72-VlVo90qJJ_j-2bVPmb42CcifrA',
    appId: '1:494484064061:ios:c0ce4ae502ee87e08ce754',
    messagingSenderId: '494484064061',
    projectId: 'ecomapp-18dc3',
    storageBucket: 'ecomapp-18dc3.appspot.com',
    iosBundleId: 'com.example.ecomApp.RunnerTests',
  );
}
